### PR TITLE
Add Docker arm64 builds

### PR DESCRIPTION
**Pull request by kubo6472**

### CODE REVIEW

**Comment by tulir** [comment]
It takes 6x as long to run the docker step with this 🙀

**Comment by kubo6472** [comment]
Yes, and it still does not publish the arm64 build. There has to be some kind of better way to handle this. Maybe use a (prebuilt) arm64 binary from the normal build step? Also when I kinda forced it, I got stuck on some `$1 unknown` when trying to run it.

**Comment by kubo6472** [comment]
image
I have no idea why fly.io won't run the bridge :/

**Comment by traktuner** [comment]
> Yes, and it still does not publish the arm64 build. There has to be some kind of better way to handle this. Maybe use a (prebuilt) arm64 binary from the normal build step? Also when I kinda forced it, I got stuck on some `$1 unknown` when trying to run it.

I also had to deal with those 403 errors in the past with ghcr.io - retrying the action solved it most of the time.

Building the arm64 image works, only the push to ghcr fails:
`#36 ERROR: failed to push ghcr.io/beeper/bridge-manager:24ad59e8c96b591c61c43165087ed0c4e79cf569: unexpected status from POST request to https://ghcr.io/v2/beeper/bridge-manager/blobs/uploads/: 403 Forbidden`

**Pull request closed without merging**
